apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-deployment
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-deployment
  template:
    metadata:
      labels:
        app: nginx-deployment
    spec:
      containers:
      - name: nginx-deployment
        image: nginx:latest
        resources:
          limits:
            memory: "1G"
            cpu: "500m"
        livenessProbe:
            httpGet:
              path: /vagrant
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 1
---
  apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: nginx-nodeport
    name: nginx-nodeport
  spec:
    selector:
      app: nginx-nodeport
    type: NodePort
    ports:
    - port: 80
      targetPort: 8080
      nodePort: 31000
  
